#!/usr/bin/env python3
"""
Generate reference decode data using the RISC-V assembler.

The reference is riscv64-unknown-elf-as, NOT a hand-written model. Same
discipline as the UVM scoreboards: a model written by the same person who
wrote the DUT inherits that person's misreadings. Here the encodings come from
the toolchain that compilers actually target.

Emits a C header of {encoding, expected fields} for the Verilator harness.
"""
import subprocess, tempfile, pathlib, sys, re, random

AS      = "riscv64-unknown-elf-as"
OBJDUMP = "riscv64-unknown-elf-objdump"

R_OPS = ["add","sub","sll","slt","sltu","xor","srl","sra","or","and"]
I_OPS = ["addi","slti","sltiu","xori","ori","andi"]
SH_I  = ["slli","srli","srai"]
LOADS = ["lb","lh","lw","lbu","lhu"]
STORES= ["sb","sh","sw"]
BRANCH= ["beq","bne","blt","bge","bltu","bgeu"]

def assemble(lines):
    """Assemble a list of instructions, return their 32-bit encodings in order."""
    with tempfile.TemporaryDirectory() as d:
        src = pathlib.Path(d) / "t.S"
        obj = pathlib.Path(d) / "t.o"
        src.write_text(".text\n.globl _start\n_start:\n" +
                       "\n".join("    " + l for l in lines) + "\n")
        r = subprocess.run([AS, "-march=rv32i", "-mabi=ilp32",
                            str(src), "-o", str(obj)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stderr, file=sys.stderr)
            sys.exit(1)
        r = subprocess.run([OBJDUMP, "-d", "--no-show-raw-insn", "-M", "numeric",
                            str(obj)], capture_output=True, text=True)
        r2 = subprocess.run([OBJDUMP, "-d", str(obj)],
                            capture_output=True, text=True)
        encs = []
        for line in r2.stdout.splitlines():
            m = re.match(r'\s+[0-9a-f]+:\s+([0-9a-f]{8})\s+', line)
            if m:
                encs.append(int(m.group(1), 16))
        return encs

def main():
    rnd = random.Random(20260813)
    cases = []          # (asm_text, encoding)

    def add(lines):
        encs = assemble(lines)
        assert len(encs) == len(lines), \
            f"expected {len(lines)} encodings, got {len(encs)}"
        cases.extend(zip(lines, encs))

    # Register-register: every op, randomised registers.
    add([f"{op} x{rnd.randrange(32)}, x{rnd.randrange(32)}, x{rnd.randrange(32)}"
         for op in R_OPS for _ in range(4)])

    # Register-immediate, including the sign-extension boundaries.
    imms = [0, 1, -1, 2047, -2048, 5, -5]
    add([f"{op} x{rnd.randrange(32)}, x{rnd.randrange(32)}, {i}"
         for op in I_OPS for i in imms])

    # Shift-immediate: 0, 1, 31 are the interesting shift amounts.
    add([f"{op} x{rnd.randrange(32)}, x{rnd.randrange(32)}, {s}"
         for op in SH_I for s in (0, 1, 15, 31)])

    # Upper immediate.
    add([f"lui x{rnd.randrange(32)}, {v}"   for v in (0, 1, 0xFFFFF, 0x12345)])
    add([f"auipc x{rnd.randrange(32)}, {v}" for v in (0, 1, 0xFFFFF, 0x12345)])

    # Loads and stores, offsets at the sign boundary.
    offs = [0, 4, -4, 2047, -2048]
    add([f"{op} x{rnd.randrange(32)}, {o}(x{rnd.randrange(32)})"
         for op in LOADS for o in offs])
    add([f"{op} x{rnd.randrange(32)}, {o}(x{rnd.randrange(32)})"
         for op in STORES for o in offs])

    # Branches. Offsets must be even; use a local label at a known distance.
    for op in BRANCH:
        for off in (4, 8, -4, 2044, -2048):
            lines = []
            if off > 0:
                lines.append(f"{op} x1, x2, .+{off}")
            else:
                lines.append(f"{op} x1, x2, .{off}")
            add(lines)

    # Jumps.
    for off in (4, 8, -4, 1048572, -1048576):
        add([f"jal x{rnd.randrange(32)}, .+{off}" if off > 0
             else f"jal x{rnd.randrange(32)}, .{off}"])
    add([f"jalr x{rnd.randrange(32)}, {o}(x{rnd.randrange(32)})"
         for o in (0, 4, -4, 2047, -2048)])

    # System and fence.
    add(["ecall", "ebreak", "fence", "fence.i"])

    out = pathlib.Path(__file__).parent / "ref_cases.h"
    with out.open("w") as f:
        f.write("// GENERATED by gen_ref.py - do not edit.\n")
        f.write("// Encodings produced by riscv64-unknown-elf-as, an\n")
        f.write("// independent reference. Regenerate with: make ref\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct { uint32_t enc; const char *asm_text; } ref_case_t;\n\n")
        f.write("static const ref_case_t ref_cases[] = {\n")
        for txt, enc in cases:
            f.write(f'    {{0x{enc:08x}u, "{txt}"}},\n')
        f.write("};\n\n")
        f.write(f"static const int n_ref_cases = {len(cases)};\n")
    print(f"wrote {len(cases)} reference cases to {out}")

if __name__ == "__main__":
    main()
